apiVersion: v1
kind: Service
metadata:
  name: netsentry-api
  namespace: netsentry-system
  labels:
    app.kubernetes.io/name: netsentry
    app.kubernetes.io/instance: netsentry-engine
spec:
  type: ClusterIP
  ports:
    - name: http-api
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: netsentry
    app.kubernetes.io/instance: netsentry-engine
